attack_technique: Test
display_name: Shell History Tampering
atomic_tests:
- name: Test
  description: Test
  supported_platforms:
    - linux
    - containers
  executor:
    command: |
      export HISTIGNORE="touch*"
      touch /tmp/temporary_test_file
    cleanup_command: |
      unset HISTIGNORE
      rm /tmp/temporary_test_file
    name: bash
    elevation_required: false
