attack_technique: Test
display_name: Suspicious Network Tool in Container
atomic_tests:
- name: Test
  description: Test
  supported_platforms:
    - linux
    - containers
  executor:
    command: |
      nmap -sn 172.17.0.0/26
    name: bash
    elevation_required: false
