attack_technique: Test
display_name: Contact EC2 Instance Metadata Service
atomic_tests:
- name: Test
  description: Test
  supported_platforms:
    - linux
    - containers
  executor:
    command: |
      wget -qO- 169.254.169.254/latest/meta-data/
    name: bash
    elevation_required: false
