attack_technique: Test
display_name: Find Azure Credentials
atomic_tests:
- name: Test
  description: Test
  supported_platforms:
    - linux
    - containers
  executor:
    command: |
      find /home /root /etc -wholename '*azure.json'
    name: bash
    elevation_required: false
