attack_technique: Test
display_name: Find AWS Credentials
atomic_tests:
- name: Test
  description: Test
  supported_platforms:
    - linux
    - containers
  executor:
    command: |
      find /home /root -wholename '*.aws/credentials'
    name: bash
    elevation_required: false
