attack_technique: Test
display_name: Read Environment Variable from /proc files
atomic_tests:
- name: Test
  description: Test
  supported_platforms:
    - linux
    - containers
  executor:
    command: |
      SECRET=secret sleep 100 & PID=$!
      cat /proc/$PID/environ | tr "\0" "\n" | grep SECRET
      kill -9 $PID
      wait $PID 2>/dev/null
    name: bash
    elevation_required: false
